### PR TITLE
Update CODPM-API-Discord.js

### PR DESCRIPTION
**Pull request by syszkc**
Fixed player count by excluding the bots.
Replaced no-named servers with "Unnamed Server"

### CODE REVIEW

**Comment by cato-a** [comment]
Hi, thanks for the contribution.

However `camelCase` is not consistent with the project and renaming the `sv_hostname` looks to me it would break the calculation for the width in the "Server Name" column.

Whether or not empty hostnames should be renamed or not is a matter of preference. I prefer the names to be as they are.

The suggested fix for the players to not display bots can be fixed this way:

Change: 

https://github.com/cato-a/CODPM-API-Discord/blob/43ebffd0991b43156002d9be919599ff9fba6bd7/CODPM-API-Discord.js#L92-L94

To:

```javascript
                    const players = server.playerinfo.length - server.bots;
                    if(players > 0) {
                        globalplayers += players;
```

Perhaps empty `sv_hostname` could be a configurable option e.g `const RENAME_EMPTY = 'Unnamed Server'` and the following:

Change:

https://github.com/cato-a/CODPM-API-Discord/blob/43ebffd0991b43156002d9be919599ff9fba6bd7/CODPM-API-Discord.js#L98-L99

To:

```javascript
                        let sv_hostname = server.sv_hostname.replace(/[^\x20-\x7E]+/g, '').replace(/^\s+|\s+$|(\s)\1+/g, (m, c) => c ? c : '');
                        sv_hostname = truncate(monotone(sv_hostname), hlength).replace(/(discord)|`/ig, (m, c) => c ? 'disсord' : '`');
                        sv_hostname = !sv_hostname && RENAME_EMPTY ? RENAME_EMPTY : sv_hostname;
```

**Comment by syszkc** [comment]
Cool, thanks for clarifying! :)

**Comment by cato-a** [comment]
I've added the changes, maybe you can double check they are working as intended.

https://github.com/cato-a/CODPM-API-Discord/commit/10f1f6879387926f3331e73e6942ce6c0895b26a

**Comment by syszkc** [comment]
The changes are fine but I just noticed that the **globalservers** should be filtered as well and shouldn't include the filtered servers (server.hidden == 1 || sv_maxclients > 72)

Edit: I misread the code, I meant to refer to `${rawj.servers.length}` variable.

**Comment by cato-a** [comment]
I guess the best way to do that is to add a `totalservers` variable to the line below and increase the array size to 8.

https://github.com/cato-a/CODPM-API-Discord/blob/10f1f6879387926f3331e73e6942ce6c0895b26a/CODPM-API-Discord.js#L85

Followed by incrementing that variable after the `continue;` statement and finally replace the `rawj.servers.length` with `totalservers`.

**Pull request closed without merging**
